spring:
  docker:
    compose:
      enabled: false

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  structured:
    format:
      console: ecs
  level:
    root: INFO

management:
  endpoint:
    health:
      show-details: never
  tracing:
    sampling:
      probability: 0.1
