packages:
  - apps/*
  - packages/*

overrides:
  vite: ^8.0.0

minimumReleaseAge: 0

allowBuilds:
  '@carbon/icons': true
  '@parcel/watcher': true
  '@scarf/scarf': false
  '@swc/core': true
  '@tailwindcss/oxide': true
  esbuild: true
  sharp: false
  unrs-resolver: false
