# -*- coding: utf-8 -*-
"""Generate the petclinic GKE manifests (base). Run from repo root:
    python k8s/_generate.py
Emits Deployment + Service per microservice into k8s/base/.
Stateful infra (Postgres, RabbitMQ, Redis, MinIO, Camunda+ES) and the LGTM
observability stack live OFF-cluster on VMs — see k8s/infra-vm/.
"""
import io, os

BASE = os.path.join(os.path.dirname(__file__), "base")
os.makedirs(BASE, exist_ok=True)

NS = "petclinic"

# name, app_port, mgmt_port, kind, mem_req, mem_lim, extra_env(list of (k,v)), needs_db
SPRING = "spring"
GO = "go"

PLATFORM = [
    # config-server: native filesystem profile, no eureka/db
    dict(name="config-server", app=8888, mgmt=9888, kind=SPRING, mem=("256Mi", "512Mi"),
         profile="native,gke", common=False,
         env=[("SPRING_PROFILES_ACTIVE", "native,gke"),
              ("SPRING_DOCKER_COMPOSE_ENABLED", "false"),
              ("OTLP_ENDPOINT", "http://otel-collector:4318/v1/traces"),
              ("JWKS_URI", "http://auth-service:8183/.well-known/jwks.json")]),
    dict(name="discovery-server", app=8761, mgmt=9761, kind=SPRING, mem=("256Mi", "512Mi"),
         profile="gke", common=False,
         env=[("SPRING_PROFILES_ACTIVE", "gke"),
              ("SPRING_DOCKER_COMPOSE_ENABLED", "false"),
              ("CONFIG_SERVER_URL", "http://config-server:8888"),
              ("OTLP_ENDPOINT", "http://otel-collector:4318/v1/traces"),
              ("JWKS_URI", "http://auth-service:8183/.well-known/jwks.json")]),
    dict(name="admin-server", app=8185, mgmt=9185, kind=SPRING, mem=("256Mi", "512Mi"),
         profile="gke", common=True,
         env=[("ADMIN_USER", "admin")],
         secret_env=[("ADMIN_PASSWORD", "ADMIN_PASSWORD")]),
]

APPS = [
    dict(name="api-gateway", app=8180, mgmt=9080, kind=SPRING, mem=("384Mi", "768Mi"), common=True),
    dict(name="auth-service", app=8183, mgmt=9183, kind=SPRING, mem=("384Mi", "768Mi"), common=True,
         secret_env=[("ADMIN_PASSWORD", "ADMIN_PASSWORD")]),
    dict(name="customers-service", app=8181, mgmt=9181, kind=SPRING, mem=("384Mi", "768Mi"), common=True),
    dict(name="vets-service", app=8182, mgmt=9182, kind=SPRING, mem=("384Mi", "768Mi"), common=True,
         env=[("MINIO_ENDPOINT", "http://minio:9000")]),
    dict(name="visits-service", app=8184, mgmt=9184, kind=SPRING, mem=("384Mi", "768Mi"), common=True),
    dict(name="reviews-service", app=8189, mgmt=9189, kind=SPRING, mem=("384Mi", "768Mi"), common=True),
    dict(name="genai-service", app=8188, mgmt=9188, kind=SPRING, mem=("512Mi", "1024Mi"), common=True,
         env=[("SPRING_DATASOURCE_URL", "jdbc:postgresql://postgres:5432/petclinic?currentSchema=genai"),
              ("PETCLINIC_LLM_BASE_URL", "https://openrouter.ai/api/v1"),
              ("PETCLINIC_LLM_CHAT_MODEL", "anthropic/claude-3.5-haiku"),
              ("PETCLINIC_EMBEDDING_BASE_URL", "https://api.openai.com/v1"),
              ("PETCLINIC_EMBEDDING_MODEL", "text-embedding-3-small")],
         secret_env=[("PETCLINIC_LLM_API_KEY", "PETCLINIC_LLM_API_KEY"),
                     ("PETCLINIC_EMBEDDING_API_KEY", "PETCLINIC_EMBEDDING_API_KEY"),
                     ("PETCLINIC_CRYPTO_KEY", "PETCLINIC_CRYPTO_KEY")]),
    dict(name="mcp-server", app=8187, mgmt=9187, kind=SPRING, mem=("384Mi", "768Mi"), common=True),
    dict(name="workflow-service", app=8190, mgmt=9190, kind=SPRING, mem=("384Mi", "768Mi"), common=True,
         env=[("CAMUNDA_CLIENT_ZEEBE_GRPCADDRESS", "http://camunda:26500"),
              ("CAMUNDA_CLIENT_MODE", "selfmanaged")]),
    # products-service owns catalogue + stock + pricing (inventory is a role/UC, not a service)
    dict(name="products-service", app=8191, mgmt=9191, kind=SPRING, mem=("384Mi", "768Mi"), common=True),
    dict(name="billing-service", app=8192, mgmt=9192, kind=SPRING, mem=("384Mi", "768Mi"), common=True),
]

# Go services (lightweight, no Spring actuator). files-service = media/PDF over MinIO.
GO = [
    dict(name="mailer-service", app=8186, mem=("64Mi", "128Mi"), env=[
        ("AMQP_URL", "amqp://guest:guest@rabbitmq:5672/"),
        ("REDIS_ADDR", "redis:6379"),
        ("SMTP_HOST", "smtp"), ("SMTP_PORT", "1025"),
        ("ADMIN_SERVER_URL", "http://admin-server:8185"),
        ("ADMIN_PUBLIC_HOST", "mailer-service"), ("ADMIN_USER", "admin"),
    ], secret_env=[("ADMIN_PASSWORD", "ADMIN_PASSWORD")]),
    dict(name="files-service", app=8193, mem=("64Mi", "128Mi"), env=[
        ("MINIO_ENDPOINT", "http://minio:9000"),
        ("MINIO_BUCKET_PETS", "pet-photos"), ("MINIO_BUCKET_INVOICES", "invoices"),
    ], secret_env=[("MINIO_ACCESS_KEY", "MINIO_ACCESS_KEY"),
                   ("MINIO_SECRET_KEY", "MINIO_SECRET_KEY")]),
]

HEADER = "# GENERATED by k8s/_generate.py — edit the generator, not this file.\n"


def spring_probes(mgmt):
    return f"""          startupProbe:
            httpGet: {{ path: /actuator/health/readiness, port: {mgmt} }}
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            httpGet: {{ path: /actuator/health/readiness, port: {mgmt} }}
            periodSeconds: 10
          livenessProbe:
            httpGet: {{ path: /actuator/health/liveness, port: {mgmt} }}
            periodSeconds: 15
            failureThreshold: 5"""


def render_spring(s):
    name = s["name"]
    app, mgmt = s["app"], s["mgmt"]
    mem_req, mem_lim = s["mem"]
    common = s.get("common", True)
    env = s.get("env", [])
    secret_env = s.get("secret_env", [])

    env_lines = ""
    for k, v in env:
        env_lines += f'            - {{ name: {k}, value: "{v}" }}\n'
    for k, sk in secret_env:
        env_lines += (f"            - name: {k}\n"
                      f"              valueFrom: {{ secretKeyRef: {{ name: petclinic-secrets, key: {sk} }} }}\n")
    envfrom = ""
    if common:
        envfrom = ("          envFrom:\n"
                   "            - configMapRef: { name: petclinic-common }\n")
    env_block = ""
    if env_lines:
        env_block = "          env:\n" + env_lines

    return f"""{HEADER}apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  labels: {{ app: {name}, tier: {"platform" if s in PLATFORM else "app"} }}
spec:
  replicas: 1
  selector: {{ matchLabels: {{ app: {name} }} }}
  template:
    metadata:
      labels: {{ app: {name} }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{mgmt}"
        prometheus.io/path: /actuator/prometheus
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile: {{ type: RuntimeDefault }}
      containers:
        - name: {name}
          image: petclinic-ms/{name}:latest
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {{ drop: ["ALL"] }}
          ports:
            - {{ name: http, containerPort: {app} }}
            - {{ name: mgmt, containerPort: {mgmt} }}
{envfrom}{env_block}          resources:
            requests: {{ cpu: 200m, memory: {mem_req} }}
            limits: {{ cpu: "1", memory: {mem_lim} }}
{spring_probes(mgmt)}
---
apiVersion: v1
kind: Service
metadata:
  name: {name}
  labels: {{ app: {name} }}
spec:
  selector: {{ app: {name} }}
  ports:
    - {{ name: http, port: {app}, targetPort: {app} }}
    - {{ name: mgmt, port: {mgmt}, targetPort: {mgmt} }}
"""


def render_go(s):
    name = s["name"]
    app = s["app"]
    mem_req, mem_lim = s["mem"]
    env_lines = ""
    for k, v in s.get("env", []):
        env_lines += f'            - {{ name: {k}, value: "{v}" }}\n'
    for k, sk in s.get("secret_env", []):
        env_lines += (f"            - name: {k}\n"
                      f"              valueFrom: {{ secretKeyRef: {{ name: petclinic-secrets, key: {sk} }} }}\n")
    return f"""{HEADER}apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  labels: {{ app: {name}, tier: app }}
spec:
  replicas: 1
  selector: {{ matchLabels: {{ app: {name} }} }}
  template:
    metadata:
      labels: {{ app: {name} }}
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile: {{ type: RuntimeDefault }}
      containers:
        - name: {name}
          image: petclinic-ms/{name}:latest
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {{ drop: ["ALL"] }}
          ports:
            - {{ name: http, containerPort: {app} }}
          env:
{env_lines}          resources:
            requests: {{ cpu: 50m, memory: {mem_req} }}
            limits: {{ cpu: 250m, memory: {mem_lim} }}
          readinessProbe:
            httpGet: {{ path: /health, port: {app} }}
            periodSeconds: 10
          livenessProbe:
            httpGet: {{ path: /health, port: {app} }}
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: {name}
  labels: {{ app: {name} }}
spec:
  selector: {{ app: {name} }}
  ports:
    - {{ name: http, port: {app}, targetPort: {app} }}
"""


files = []
for s in PLATFORM + APPS:
    fn = f"{s['name']}.yaml"
    io.open(os.path.join(BASE, fn), "w", encoding="utf-8").write(render_spring(s))
    files.append(fn)
for s in GO:
    fn = f"{s['name']}.yaml"
    io.open(os.path.join(BASE, fn), "w", encoding="utf-8").write(render_go(s))
    files.append(fn)

print("generated %d service manifests:" % len(files))
for f in sorted(files):
    print("  base/" + f)
