# -*- coding: utf-8 -*-
"""Generate the petclinic GKE manifests (base). Run from repo root:
    python k8s/_generate.py
Emits Deployment + Service per microservice into k8s/base/.
Stateful infra (Postgres, RabbitMQ, Redis, MinIO, Camunda+ES) and the LGTM
observability stack live OFF-cluster on VMs — see k8s/infra-vm/.
"""
import io, os

BASE = os.path.join(os.path.dirname(__file__), "base")
os.makedirs(BASE, exist_ok=True)

NS = "petclinic"

# name, app_port, mgmt_port, kind, mem_req, mem_lim, extra_env(list of (k,v)), needs_db
SPRING = "spring"
GO = "go"

PLATFORM = [
    # config-server: native filesystem profile, no eureka/db
    dict(name="config-server", app=8888, mgmt=9888, kind=SPRING, mem=("256Mi", "512Mi"),
         profile="native,gke", common=False,
         env=[("SPRING_PROFILES_ACTIVE", "native,gke"),
              ("SPRING_DOCKER_COMPOSE_ENABLED", "false"),
              ("OTLP_ENDPOINT", "http://otel-collector:4318/v1/traces"),
              ("JWKS_URI", "http://auth-service:8183/.well-known/jwks.json")]),
    dict(name="discovery-server", app=8761, mgmt=9761, kind=SPRING, mem=("256Mi", "512Mi"),
         profile="gke", common=False,
         env=[("SPRING_PROFILES_ACTIVE", "gke"),
              ("SPRING_DOCKER_COMPOSE_ENABLED", "false"),
              ("CONFIG_SERVER_URL", "http://config-server:8888"),
              ("OTLP_ENDPOINT", "http://otel-collector:4318/v1/traces"),
              ("JWKS_URI", "http://auth-service:8183/.well-known/jwks.json")]),
    dict(name="admin-server", app=8185, mgmt=9185, kind=SPRING, mem=("256Mi", "512Mi"),
         profile="gke", common=True,
         env=[("ADMIN_USER", "admin")],
         secret_env=[("ADMIN_PASSWORD", "ADMIN_PASSWORD")]),
]

APPS = [
    dict(name="api-gateway", app=8180, mgmt=9080, kind=SPRING, mem=("384Mi", "768Mi"), common=True),
    dict(name="auth-service", app=8183, mgmt=9183, kind=SPRING, mem=("384Mi", "768Mi"), common=True,
         secret_env=[("ADMIN_PASSWORD", "ADMIN_PASSWORD")]),
    dict(name="customers-service", app=8181, mgmt=9181, kind=SPRING, mem=("384Mi", "768Mi"), common=True),
    dict(name="vets-service", app=8182, mgmt=9182, kind=SPRING, mem=("384Mi", "768Mi"), common=True,
         env=[("MINIO_ENDPOINT", "http://minio:9000")]),
    dict(name="visits-service", app=8184, mgmt=9184, kind=SPRING, mem=("384Mi", "768Mi"), common=True),
    dict(name="reviews-service", app=8189, mgmt=9189, kind=SPRING, mem=("384Mi", "768Mi"), common=True),
    dict(name="genai-service", app=8188, mgmt=9188, kind=SPRING, mem=("512Mi", "1024Mi"), common=True,
         env=[("SPRING_DATASOURCE_URL", "jdbc:postgresql://postgres:5432/petclinic?currentSchema=genai"),
              ("PETCLINIC_LLM_BASE_URL", "https://openrouter.ai/api/v1"),
              ("PETCLINIC_LLM_CHAT_MODEL", "anthropic/claude-3.5-haiku"),
              ("PETCLINIC_EMBEDDING_BASE_URL", "https://api.openai.com/v1"),
              ("PETCLINIC_EMBEDDING_MODEL", "text-embedding-3-small")],
         secret_env=[("PETCLINIC_LLM_API_KEY", "PETCLINIC_LLM_API_KEY"),
                     ("PETCLINIC_EMBEDDING_API_KEY", "PETCLINIC_EMBEDDING_API_KEY"),
                     ("PETCLINIC_CRYPTO_KEY", "PETCLINIC_CRYPTO_KEY")]),
    dict(name="mcp-server", app=8187, mgmt=9187, kind=SPRING, mem=("384Mi", "768Mi"), common=True),
    dict(name="workflow-service", app=8190, mgmt=9190, kind=SPRING, mem=("384Mi", "768Mi"), common=True,
         env=[("CAMUNDA_CLIENT_ZEEBE_GRPCADDRESS", "http://camunda:26500"),
              ("CAMUNDA_CLIENT_MODE", "selfmanaged")]),
]

MAILER = dict(name="mailer-service", app=8186, kind=GO, mem=("64Mi", "128Mi"))

HEADER = "# GENERATED by k8s/_generate.py — edit the generator, not this file.\n"


def spring_probes(mgmt):
    return f"""          startupProbe:
            httpGet: {{ path: /actuator/health/readiness, port: {mgmt} }}
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            httpGet: {{ path: /actuator/health/readiness, port: {mgmt} }}
            periodSeconds: 10
          livenessProbe:
            httpGet: {{ path: /actuator/health/liveness, port: {mgmt} }}
            periodSeconds: 15
            failureThreshold: 5"""


def render_spring(s):
    name = s["name"]
    app, mgmt = s["app"], s["mgmt"]
    mem_req, mem_lim = s["mem"]
    common = s.get("common", True)
    env = s.get("env", [])
    secret_env = s.get("secret_env", [])

    env_lines = ""
    for k, v in env:
        env_lines += f'            - {{ name: {k}, value: "{v}" }}\n'
    for k, sk in secret_env:
        env_lines += (f"            - name: {k}\n"
                      f"              valueFrom: {{ secretKeyRef: {{ name: petclinic-secrets, key: {sk} }} }}\n")
    envfrom = ""
    if common:
        envfrom = ("          envFrom:\n"
                   "            - configMapRef: { name: petclinic-common }\n")
    env_block = ""
    if env_lines:
        env_block = "          env:\n" + env_lines

    return f"""{HEADER}apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  labels: {{ app: {name}, tier: {"platform" if s in PLATFORM else "app"} }}
spec:
  replicas: 1
  selector: {{ matchLabels: {{ app: {name} }} }}
  template:
    metadata:
      labels: {{ app: {name} }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{mgmt}"
        prometheus.io/path: /actuator/prometheus
    spec:
      containers:
        - name: {name}
          image: petclinic-ms/{name}:latest
          ports:
            - {{ name: http, containerPort: {app} }}
            - {{ name: mgmt, containerPort: {mgmt} }}
{envfrom}{env_block}          resources:
            requests: {{ cpu: 200m, memory: {mem_req} }}
            limits: {{ cpu: "1", memory: {mem_lim} }}
{spring_probes(mgmt)}
---
apiVersion: v1
kind: Service
metadata:
  name: {name}
  labels: {{ app: {name} }}
spec:
  selector: {{ app: {name} }}
  ports:
    - {{ name: http, port: {app}, targetPort: {app} }}
    - {{ name: mgmt, port: {mgmt}, targetPort: {mgmt} }}
"""


def render_mailer(s):
    name = s["name"]
    app = s["app"]
    mem_req, mem_lim = s["mem"]
    return f"""{HEADER}apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  labels: {{ app: {name}, tier: app }}
spec:
  replicas: 1
  selector: {{ matchLabels: {{ app: {name} }} }}
  template:
    metadata:
      labels: {{ app: {name} }}
    spec:
      containers:
        - name: {name}
          image: petclinic-ms/{name}:latest
          ports:
            - {{ name: http, containerPort: {app} }}
          env:
            - {{ name: AMQP_URL, value: "amqp://guest:guest@rabbitmq:5672/" }}
            - {{ name: REDIS_ADDR, value: "redis:6379" }}
            - {{ name: SMTP_HOST, value: "smtp" }}
            - {{ name: SMTP_PORT, value: "1025" }}
            - {{ name: ADMIN_SERVER_URL, value: "http://admin-server:8185" }}
            - {{ name: ADMIN_PUBLIC_HOST, value: "mailer-service" }}
            - {{ name: ADMIN_USER, value: "admin" }}
            - name: ADMIN_PASSWORD
              valueFrom: {{ secretKeyRef: {{ name: petclinic-secrets, key: ADMIN_PASSWORD }} }}
          resources:
            requests: {{ cpu: 50m, memory: {mem_req} }}
            limits: {{ cpu: 250m, memory: {mem_lim} }}
          readinessProbe:
            httpGet: {{ path: /health, port: {app} }}
            periodSeconds: 10
          livenessProbe:
            httpGet: {{ path: /health, port: {app} }}
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: {name}
  labels: {{ app: {name} }}
spec:
  selector: {{ app: {name} }}
  ports:
    - {{ name: http, port: {app}, targetPort: {app} }}
"""


files = []
for s in PLATFORM + APPS:
    fn = f"{s['name']}.yaml"
    io.open(os.path.join(BASE, fn), "w", encoding="utf-8").write(render_spring(s))
    files.append(fn)
io.open(os.path.join(BASE, "mailer-service.yaml"), "w", encoding="utf-8").write(render_mailer(MAILER))
files.append("mailer-service.yaml")

print("generated %d service manifests:" % len(files))
for f in sorted(files):
    print("  base/" + f)
