blank_issues_enabled: false
contact_links:
  - name: Question / discussion
    url: https://github.com/kl3inIT/petclinic-ms/discussions
    about: Hỏi general questions hoặc thảo luận thiết kế ở Discussions (nếu enable).
