type Replacements = Record<string, string | number>;

const TRANSLATIONS: Record<string, string> = {
  // bpmn-js palette / context pad
  'Activate hand tool': 'Công cụ kéo tay',
  'Activate lasso tool': 'Công cụ chọn vùng',
  'Activate create/remove space tool': 'Thêm/xóa khoảng trống',
  'Activate global connect tool': 'Công cụ nối toàn cục',
  'Create start event': 'Tạo sự kiện bắt đầu',
  'Create intermediate/boundary event': 'Tạo sự kiện trung gian/biên',
  'Create end event': 'Tạo sự kiện kết thúc',
  'Create gateway': 'Tạo cổng rẽ nhánh',
  'Create task': 'Tạo tác vụ',
  'Create data object reference': 'Tạo đối tượng dữ liệu',
  'Create data store reference': 'Tạo kho dữ liệu',
  'Create expanded sub-process': 'Tạo quy trình con mở rộng',
  'Create pool/participant': 'Tạo pool/participant',
  'Create group': 'Tạo nhóm',
  'Create user task': 'Tạo tác vụ người dùng',
  'Create service task': 'Tạo tác vụ dịch vụ',
  'Create send task': 'Tạo tác vụ gửi',
  'Create receive task': 'Tạo tác vụ nhận',
  'Create manual task': 'Tạo tác vụ thủ công',
  'Create business rule task': 'Tạo tác vụ luật nghiệp vụ',
  'Create script task': 'Tạo tác vụ script',
  'Append end event': 'Thêm sự kiện kết thúc',
  'Append gateway': 'Thêm cổng rẽ nhánh',
  'Append task': 'Thêm tác vụ',
  'Append receive task': 'Thêm tác vụ nhận',
  'Append message intermediate catch event': 'Thêm sự kiện nhận thông điệp',
  'Append timer intermediate catch event': 'Thêm sự kiện thời gian',
  'Append conditional intermediate catch event': 'Thêm sự kiện điều kiện',
  'Append signal intermediate catch event': 'Thêm sự kiện tín hiệu',
  'Append compensation activity': 'Thêm hoạt động bù trừ',
  'Append intermediate/boundary event': 'Thêm sự kiện trung gian/biên',
  'Change element': 'Đổi loại phần tử',
  'Connect to other element': 'Nối đến phần tử khác',
  'Connect using association': 'Nối bằng association',
  'Connect using data input association': 'Nối bằng data input association',
  'Add text annotation': 'Thêm ghi chú',
  Delete: 'Xóa',
  Remove: 'Xóa',
  'Add lane above': 'Thêm lane phía trên',
  'Add lane below': 'Thêm lane phía dưới',
  'Divide into two lanes': 'Chia thành hai lane',
  'Divide into three lanes': 'Chia thành ba lane',
  'Align elements': 'Căn chỉnh phần tử',
  'Align elements left': 'Căn trái',
  'Align elements right': 'Căn phải',
  'Align elements center': 'Căn giữa',
  'Align elements top': 'Căn trên',
  'Align elements bottom': 'Căn dưới',
  'Align elements middle': 'Căn giữa dọc',
  'Distribute elements horizontally': 'Phân bố ngang',
  'Distribute elements vertically': 'Phân bố dọc',

  // BPMN element names
  'Start Event': 'Sự kiện bắt đầu',
  'Intermediate Throw Event': 'Sự kiện ném trung gian',
  'Intermediate Catch Event': 'Sự kiện bắt trung gian',
  'End Event': 'Sự kiện kết thúc',
  Task: 'Tác vụ',
  'User Task': 'Tác vụ người dùng',
  'Service Task': 'Tác vụ dịch vụ',
  'Send Task': 'Tác vụ gửi',
  'Receive Task': 'Tác vụ nhận',
  'Manual Task': 'Tác vụ thủ công',
  'Business Rule Task': 'Tác vụ luật nghiệp vụ',
  'Script Task': 'Tác vụ script',
  'Call Activity': 'Gọi quy trình',
  'Sub Process': 'Quy trình con',
  'Exclusive Gateway': 'Cổng loại trừ',
  'Parallel Gateway': 'Cổng song song',
  'Inclusive Gateway': 'Cổng bao gồm',
  'Event Based Gateway': 'Cổng theo sự kiện',
  'Complex Gateway': 'Cổng phức hợp',
  'Sequence Flow': 'Luồng tuần tự',
  'Message Flow': 'Luồng thông điệp',
  'Data Object Reference': 'Tham chiếu đối tượng dữ liệu',
  'Data Store Reference': 'Tham chiếu kho dữ liệu',
  'Text Annotation': 'Ghi chú',
  Group: 'Nhóm',
  Participant: 'Participant',
  Lane: 'Lane',
  'Collapsed Pool': 'Pool thu gọn',
  'Expanded Pool': 'Pool mở rộng',

  // Properties panel groups / fields
  General: 'Chung',
  Documentation: 'Tài liệu',
  'Extension properties': 'Thuộc tính mở rộng',
  'Execution listeners': 'Listener thực thi',
  'Task listeners': 'Listener tác vụ',
  'Job execution': 'Thực thi job',
  'Candidate starter': 'Người có quyền khởi chạy',
  'External task': 'External task',
  Tasklist: 'Tasklist',
  'History cleanup': 'Dọn lịch sử',
  Details: 'Chi tiết',
  Process: 'Quy trình',
  'Process ID': 'ID quy trình',
  'Process name': 'Tên quy trình',
  Name: 'Tên',
  ID: 'ID',
  Id: 'ID',
  Key: 'Mã',
  Type: 'Loại',
  Value: 'Giá trị',
  Values: 'Giá trị',
  Expression: 'Biểu thức',
  Description: 'Mô tả',
  Version: 'Phiên bản',
  Tenant: 'Tenant',
  'Tenant ID': 'ID tenant',
  'Element ID': 'ID phần tử',
  'Element type': 'Loại phần tử',
  Assignment: 'Phân công',
  Assignee: 'Người phụ trách',
  'Candidate users': 'Người dùng ứng viên',
  'Candidate groups': 'Nhóm ứng viên',
  'Candidate starter users': 'Người dùng được khởi chạy',
  'Candidate starter groups': 'Nhóm được khởi chạy',
  Forms: 'Biểu mẫu',
  'Form key': 'Khóa biểu mẫu',
  'Form reference': 'Tham chiếu biểu mẫu',
  'Form ID': 'ID biểu mẫu',
  Binding: 'Kiểu binding',
  Latest: 'Mới nhất',
  Deployment: 'Theo bản deploy',
  'Version tag': 'Thẻ phiên bản',
  'Due date': 'Ngày hạn',
  'Follow up date': 'Ngày nhắc',
  Priority: 'Độ ưu tiên',
  'Task definition': 'Định nghĩa tác vụ',
  'Task definition type': 'Loại định nghĩa tác vụ',
  'Job type': 'Loại job',
  Retries: 'Số lần thử lại',
  'Retry time cycle': 'Chu kỳ thử lại',
  Headers: 'Header',
  'Task headers': 'Header tác vụ',
  'Input/Output': 'Vào/Ra',
  Inputs: 'Đầu vào',
  Outputs: 'Đầu ra',
  'Input parameters': 'Tham số đầu vào',
  'Output parameters': 'Tham số đầu ra',
  'Input variable': 'Biến đầu vào',
  'Output variable': 'Biến đầu ra',
  'Called element': 'Phần tử được gọi',
  'Called decision': 'Quyết định được gọi',
  'Decision ID': 'ID quyết định',
  'Result variable': 'Biến kết quả',
  'Map decision result': 'Ánh xạ kết quả quyết định',
  'Message name': 'Tên thông điệp',
  'Signal name': 'Tên tín hiệu',
  Condition: 'Điều kiện',
  'Condition type': 'Loại điều kiện',
  'Condition expression': 'Biểu thức điều kiện',
  'Expression language': 'Ngôn ngữ biểu thức',
  'Default flow': 'Luồng mặc định',
  'Variable name': 'Tên biến',
  'Variable value': 'Giá trị biến',
  'Result expression': 'Biểu thức kết quả',
  'Feel expression': 'Biểu thức FEEL',
  'FEEL expression': 'Biểu thức FEEL',
  'Element documentation': 'Tài liệu phần tử',
  'Process documentation': 'Tài liệu quy trình',
  'Add property': 'Thêm thuộc tính',
  'Add entry': 'Thêm dòng',
  'Add constraint': 'Thêm ràng buộc',
  'Create new list item': 'Thêm dòng mới',
  'Remove list item': 'Xóa dòng',
  'No entries': 'Chưa có dữ liệu',
  'No variables defined.': 'Chưa định nghĩa biến.',
  'No properties configured.': 'Chưa cấu hình thuộc tính.',
  'No headers configured.': 'Chưa cấu hình header.',
  'No inputs configured.': 'Chưa cấu hình đầu vào.',
  'No outputs configured.': 'Chưa cấu hình đầu ra.',
  'Open minimap': 'Mở bản đồ nhỏ',
  'Close minimap': 'Đóng bản đồ nhỏ',
  'Connect to a different element': 'Nối tới phần tử khác',
  'Replace with': 'Thay bằng',
  'Append element': 'Thêm phần tử',

  // Generic UI in properties panel
  Add: 'Thêm',
  Save: 'Lưu',
  Cancel: 'Hủy',
  Close: 'Đóng',
  Edit: 'Sửa',
  Clear: 'Xóa lọc',
  Reset: 'Đặt lại',
  Apply: 'Áp dụng',
  Search: 'Tìm kiếm',
  Select: 'Chọn',
  'Select an element': 'Chọn một phần tử',
  'List is empty': 'Danh sách trống',
  'Text color': 'Màu chữ',
  'Background color': 'Màu nền',
  'Border color': 'Màu viền',
  'Create new': 'Tạo mới',
  Open: 'Mở',
  Copy: 'Sao chép',
  Paste: 'Dán',
  Cut: 'Cắt',
  Undo: 'Hoàn tác',
  Redo: 'Làm lại',
};

function interpolate(template: string, replacements?: Replacements) {
  if (!replacements) return template;
  return Object.entries(replacements).reduce(
    (result, [key, value]) => result.replaceAll(`{${key}}`, String(value)),
    template,
  );
}

function vietnameseTranslate(template: string, replacements?: Replacements) {
  return interpolate(TRANSLATIONS[template] ?? template, replacements);
}

export const BpmnVietnameseModule = {
  translate: ['value', vietnameseTranslate],
};
